<a href="https://colab.research.google.com/github/AzadMehedi/Numpy/blob/main/Advanced_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy array vs Python list

In [ ]:
# Speed
#list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []

import time
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i]) 
print(time.time()-start)


2.4041149616241455


In [ ]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.021371841430664062


In [ ]:
2.4041149616241455/0.021371841430664062
# in this calculation numpy is 112 time faster than python list

112.48983712628291

In [1]:
import numpy as np
import time
import sys

In [2]:
# memory in python list
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

81528048

In [4]:
# memory in numpy
a = np.arange(10000000, dtype=np.int8)  # can set dtype
sys.getsizeof(a)

10000104

# Advanced Indexing

In [5]:
# Normal Indexing and slicing
a = np.arange(12).reshape(4,3)
a 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
# find out 4,5,7,8
a[1:3,1:]

array([[4, 5],
       [7, 8]])

In [13]:
# fancy Indexing
# find out 1,3,4th row [ 0,  1,  2], [ 6,  7,  8], [ 9, 10, 11]

a[[0,2,3]]  # passing row index through list

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
a = np.arange(24).reshape(6,4)
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
# find out 1,3,4,6th row 
a[[0,2,3,5]]   #passing row index through list

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [22]:
# find out 1,2,3rd column 
a[:,[0,1,2]]    # all rows, 0,1,2 index as columns

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [ ]:
# Boolean Indexing