<a href="https://colab.research.google.com/github/AzadMehedi/Numpy/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [1]:
# np.array   
# 1d          --- we can call it vector
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
# 2d  ---can call it matrix

import numpy as numpy
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3d  ----- can call it tensor

import numpy as np
c = np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [6]:
# dtype
np.array([1,2,3,4], dtype='int')

[1 2 3 4]


In [7]:
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

In [8]:
np.array([1,2,3,4], dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [9]:
# np.arrange
np.arange(1,11,1)  #start->end->difference

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
# with reshape
np.arange(1,11).reshape(5,2)
# np.arange(1,11).reshape(2,5)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
# np.ones  - creating 0s
np.ones((3,4))  # 3 rows, 4 columns


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# p.zeros  - creating 1a
np.ones((5,6))  # 5 rows, 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
# np.random

np.random.random((3,4))

array([[0.65980257, 0.6432695 , 0.64342664, 0.57734685],
       [0.72470096, 0.20257782, 0.3185939 , 0.555718  ],
       [0.63975467, 0.31491265, 0.6994922 , 0.23059044]])

In [33]:
# np.linspace    --linear space --do generate linearly separated value 
np.linspace(-10, 10, 10)      # lower range->upper range->number of items you want to generate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [34]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [56]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)     # how many arrays(2 2d array)  ->shape(of shape(2,2))
# print(a1)
# print(a2)
print(a3)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [44]:
# ndim ---tells us dimention
# a1.ndim
# a2.ndim
a3.ndim

3

In [47]:
# shape --- items on per dimention
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [50]:
# size    - number of elemets

# a1.size
# a2.size
a3.size



8

In [51]:
# itemsize --- how many bites occupied
# int32- 4 bytes
# int64- 8 bytes, floats = 8 bytes

a1.itemsize

8

In [53]:
# dtypes
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


# changing datatypes

In [60]:
# astype
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array operation