<a href="https://colab.research.google.com/github/AzadMehedi/Numpy/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [ ]:
# np.array   
# 1d          --- we can call it vector
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# 2d  ---can call it matrix

import numpy as numpy
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3d  ----- can call it tensor

import numpy as np
c = np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
# dtype
np.array([1,2,3,4], dtype='int')

[1 2 3 4]


In [ ]:
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4], dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
# np.arrange
np.arange(1,11,1)  #start->end->difference

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)
# np.arange(1,11).reshape(2,5)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones  - creating 0s
np.ones((3,4))  # 3 rows, 4 columns


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# p.zeros  - creating 1a
np.ones((5,6))  # 5 rows, 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# np.random

np.random.random((3,4))

array([[0.65980257, 0.6432695 , 0.64342664, 0.57734685],
       [0.72470096, 0.20257782, 0.3185939 , 0.555718  ],
       [0.63975467, 0.31491265, 0.6994922 , 0.23059044]])

In [ ]:
# np.linspace    --linear space --do generate linearly separated value 
np.linspace(-10, 10, 10)      # lower range->upper range->number of items you want to generate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)     # how many arrays(2 2d array)  ->shape(of shape(2,2))
# print(a1)
# print(a2)
print(a3)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim ---tells us dimention
# a1.ndim
# a2.ndim
a3.ndim

3

In [ ]:
# shape --- items on per dimention
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [ ]:
# size    - number of elemets

# a1.size
# a2.size
a3.size



8

In [ ]:
# itemsize --- how many bites occupied
# int32- 4 bytes
# int64- 8 bytes, floats = 8 bytes

a1.itemsize

8

In [ ]:
# dtypes
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


# changing datatypes

In [ ]:
# astype
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array operation

In [1]:
import numpy as np
a1 = np.arange(12).reshape(3,4)      #0-11
a2 = np.arange(12,24).reshape(3,4)   #12-23

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scaler operations
# arithmetic

a1*2
a1 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational

a2 > 15   # here doing itemwise comparision

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operation
# arithmetic

a1 + a2  # we can do al the operations if the size is equal

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [2]:


a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[77., 85., 69.],
       [71.,  6., 89.],
       [97., 37., 46.]])

In [12]:
from numpy.core.fromnumeric import prod
# max/min/sum/prod
np.max(a1)
np.sum(a1)
np.prod(a1)
np.max(a1, axis=1)     # 0-> col   1->row

array([85., 89., 97.])

In [16]:
# mean/median/std/var

np.mean(a1)
np.mean(a1, axis=1)
np.std(a1)
np.var(a1)

757.2098765432098

In [17]:
# trigonometric function
np.sin(a1)

array([[ 0.99952016, -0.17607562, -0.11478481],
       [ 0.95105465, -0.2794155 ,  0.86006941],
       [ 0.37960774, -0.64353813,  0.90178835]])

In [20]:
# dot product
# if the size is same. col=row, row=col

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [23]:
# log and exponent

np.log(a1)
np.exp(a1)

array([[2.75851345e+33, 8.22301271e+36, 9.25378173e+29],
       [6.83767123e+30, 4.03428793e+02, 4.48961282e+38],
       [1.33833472e+42, 1.17191424e+16, 9.49611942e+19]])

In [28]:
# round/floor/ceil

np.random.random((2,3))*100

np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)



array([[95., 63., 30.],
       [82., 48., 10.]])

# indexing and Slicing

In [2]:

import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# lets find out 6   -> row:1, col:2
a2[1,2]

6

In [9]:
# lets find out 11   -> row:1, col:3
a2[2,3]

11

In [13]:
# lets find out 4   -> row:1, col:0
a2[1,0]

4

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# lets find out 5   ->which part of 2d array?if first part then 0, if 2nd part then 1. rest is same like 2d array.
# 2nd part of 2d array. row:0, col:1

a3[1,0,1]

5

In [16]:
# lets find out 5
a3[0,1,0]

2

In [17]:
# lets find out 0
a3[0,0,0]

0

In [20]:
# lets find out 6
a3[1,1,0]

6

# Slicing

In [21]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [22]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# let's find 3 to 7  # first index including, las index excluding. just like python
a1[3:8]

array([3, 4, 5, 6, 7])

In [27]:
# let's find 3 to 7, with interval 2
a1[3:8:2]

array([3, 5, 7])

In [28]:
a2  # matrix(2d array)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
# lets find out  0 to 3
a2[0,:]   # row:0, col:all

array([0, 1, 2, 3])

In [34]:
# lets find out 3rd column
a2[:,2]

array([ 2,  6, 10])

In [38]:
# lets find out 5,6 and 9,10
a2[1: , 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
# lets find out 0,3 and 8,11
a2[::2,::3 ]


array([[ 0,  3],
       [ 8, 11]])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
# lets find out 1,3 and 9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
# lets find out 4,7
a2[1,::3]

array([4, 7])

In [71]:
# lets find out 1,2,3 and 5,6,7
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [76]:
import numpy as np
a3 = np.arange(27).reshape(3,3,3)
a3   # a3 consist of 3-2d array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
# let's find out 
#     [[ 9, 10, 11],
#      [12, 13, 14],
#      [15, 16, 17]],

a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [85]:
# let's find out 
# [[ 0,  1,  2],
# [ 3,  4,  5],
# [ 6,  7,  8]], and
 
#       [[18, 19, 20],
#       [21, 22, 23],
#       [24, 25, 26]]

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
# let's find out 2nd row of first 2d array
a3[0, 1]

array([3, 4, 5])

In [95]:
# let's find out 2nd column of second 2d array
a3[1,:,1]

array([10, 13, 16])

`note:` 
- when we need a perticular row, we need all column. 
- when we need a perticular column, we need all row. 