<a href="https://colab.research.google.com/github/AzadMehedi/Numpy/blob/main/Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([43, 82,  8, 40, 60, 93, 91, 22, 37, 65, 32, 50, 95, 15,  8])

In [2]:
# sort
np.sort(a)

array([ 8,  8, 15, 22, 32, 37, 40, 43, 50, 60, 65, 82, 91, 93, 95])

In [6]:
# decending order sort 
np.sort(a)[::-1]

array([95, 93, 91, 82, 65, 60, 50, 43, 40, 37, 32, 22, 15,  8,  8])

In [7]:
b = np.random.randint(1,100, 24).reshape(6,4)
b

array([[90, 82, 48, 83],
       [49, 38, 51, 88],
       [29, 95, 62, 44],
       [38,  3, 80, 60],
       [88, 31, 20, 70],
       [60,  4, 46, 97]])

In [8]:
# row wise sorting -> (axis=1) . its default
np.sort(b)

array([[48, 82, 83, 90],
       [38, 49, 51, 88],
       [29, 44, 62, 95],
       [ 3, 38, 60, 80],
       [20, 31, 70, 88],
       [ 4, 46, 60, 97]])

In [11]:
# column wise sorting -> (axis=0) . its default
np.sort(b, axis=0)

array([[29,  3, 20, 44],
       [38,  4, 46, 60],
       [49, 31, 48, 70],
       [60, 38, 51, 83],
       [88, 82, 62, 88],
       [90, 95, 80, 97]])

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
a = np.random.randint(1,100,15)
np.append(a, 500)

array([ 53,  73,  13,  97,  68,  22,  62,  76,  46,  27,  23,  65,  70,
        87,  53, 500])

In [16]:
# append a new col
b = np.random.randint(1,100, 24).reshape(6,4)
np.append(b,np.ones((b.shape[0],1)), axis=1)
# np.append(b,np.random.random((b.shape[0],1)), axis=1)


array([[20., 92., 50., 13.,  1.],
       [77., 64., 14., 44.,  1.],
       [60., 63., 62., 22.,  1.],
       [28., 27., 78., 27.,  1.],
       [83., 38., 94., 44.,  1.],
       [93., 42., 89., 69.,  1.]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [19]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
# vertical concatenate -> 0-> column wise
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# horizontal concatenate -> 1-> row wise
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [25]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [26]:
a

array([53, 73, 13, 97, 68, 22, 62, 76, 46, 27, 23, 65, 70, 87, 53])

In [29]:
np.expand_dims(a, axis=0)   # 0->column
# np.expand_dims(a, axis=0).shape   


(1, 15)


In [30]:
np.expand_dims(a, axis=1)
# np.expand_dims(a, axis=1).shape   



(15, 1)

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [33]:
a

array([53, 73, 13, 97, 68, 22, 62, 76, 46, 27, 23, 65, 70, 87, 53])

In [34]:
 # find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  6,  7, 11, 12, 13, 14]),)

In [35]:
# replace all values > 50 with 0
# np.where(condition, true, false)
np.where(a>50, 0, a)

array([ 0,  0, 13,  0,  0, 22,  0,  0, 46, 27, 23,  0,  0,  0,  0])

In [36]:

a = np.random.randint(1,100,50)

In [37]:
a

array([32, 22, 97, 63, 54, 56, 13, 26, 50, 46, 66, 78, 36, 69, 94, 96, 50,
       95, 51, 67, 83, 77, 68, 68, 41, 88, 14, 15, 80, 56, 89, 71, 90, 87,
       80, 86, 89, 22, 13, 20, 84, 67, 55, 59, 22, 53, 79,  8, 54, 86])

In [38]:
# replace all even values with 0
np.where(a%2==0, 0, a)

array([ 0,  0, 97, 63,  0,  0, 13,  0,  0,  0,  0,  0,  0, 69,  0,  0,  0,
       95, 51, 67, 83, 77,  0,  0, 41,  0,  0, 15,  0,  0, 89, 71,  0, 87,
        0,  0, 89,  0, 13,  0,  0, 67, 55, 59,  0, 53, 79,  0,  0,  0])

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [40]:
a = np.random.randint(1,100,50)
a

array([19, 28, 26, 33,  6, 42, 71, 44, 76,  7, 47, 98, 23, 23, 27, 38, 11,
       33, 34, 60, 29, 36, 98, 66, 81, 44, 16, 32, 63, 17, 62, 93, 82, 54,
       18, 26, 16, 32, 71, 24, 73, 18, 55, 22, 61, 29,  8, 69, 89, 94])

In [41]:
np.argmax(a)

11

In [43]:
b = np.random.randint(1,100, 24).reshape(6,4)
b

array([[51, 76, 30, 78],
       [16, 85, 73, 94],
       [42, 18, 13, 41],
       [49, 22, 38, 21],
       [49, 99, 69, 24],
       [18, 22, 68, 85]])

In [44]:
# row wise
np.argmax(b,axis=0)

array([0, 4, 1, 1])

In [47]:
print(a)
# np.argmin
np.argmin(a)

[19 28 26 33  6 42 71 44 76  7 47 98 23 23 27 38 11 33 34 60 29 36 98 66
 81 44 16 32 63 17 62 93 82 54 18 26 16 32 71 24 73 18 55 22 61 29  8 69
 89 94]


4

# np.cumsum     
cumulitive sum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [4]:
a = np.random.randint(1,100,25)
a

array([66, 98, 72, 70, 28, 64, 75, 27, 54, 66,  9, 10, 42, 82, 70, 36, 90,
       75, 22, 32, 32, 12, 74, 14, 26])

In [5]:
np.cumsum(a)

array([  66,  164,  236,  306,  334,  398,  473,  500,  554,  620,  629,
        639,  681,  763,  833,  869,  959, 1034, 1056, 1088, 1120, 1132,
       1206, 1220, 1246])

In [2]:
# for 2d array
b = np.random.randint(1,100,24).reshape(4,6)
b

array([[25, 68,  2, 88, 52,  7],
       [22, 94, 75, 34, 15, 47],
       [69, 62, 35, 26, 81, 40],
       [75, 32, 76, 22, 61, 14]])

In [54]:
np.cumsum(b)


array([  98,  130,  212,  240,  291,  336,  341,  388,  423,  463,  466,
        532,  538,  635,  647,  735,  830,  871,  918, 1016, 1073, 1116,
       1187, 1201])

In [55]:
np.cumsum(b, axis=0) # columnwise

array([[ 98,  32,  82,  28,  51,  45],
       [103,  79, 117,  68,  54, 111],
       [109, 176, 129, 156, 149, 152],
       [156, 274, 186, 199, 220, 166]])

In [56]:
np.cumsum(b, axis=1) # rowwise

array([[ 98, 130, 212, 240, 291, 336],
       [  5,  52,  87, 127, 130, 196],
       [  6, 103, 115, 203, 298, 339],
       [ 47, 145, 202, 245, 316, 330]])

In [7]:
# cumprod
np.cumprod(a)

array([                  66,                 6468,               465696,
                   32598720,            912764160,          58416906240,
              4381267968000,      118294235136000,     6387888697344000,
         421600654024704000,  3794405886222336000,  1050570714804256768,
        7230481874359681024,  2603703338788192256, -2208207021922058240,
       -5708476494355890176,  2745949571837329408,  3032033076994637824,
       -7082248600956174336, -5271026346082959360, -2652146411268734976,
        5067731212194283520,  6077228228185948160, -7152525173944483840,
       -1498213785461063680])

# np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [9]:
np.percentile(a, 50)

54.0

In [11]:
np.median(a)

54.0

# np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [12]:
a

array([66, 98, 72, 70, 28, 64, 75, 27, 54, 66,  9, 10, 42, 82, 70, 36, 90,
       75, 22, 32, 32, 12, 74, 14, 26])

In [14]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 3, 4, 3, 1, 1, 3, 6, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [15]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [16]:
a

array([66, 98, 72, 70, 28, 64, 75, 27, 54, 66,  9, 10, 42, 82, 70, 36, 90,
       75, 22, 32, 32, 12, 74, 14, 26])

In [19]:
items = [10,20,30,40,50,60,70,80,90,100]
# np.isin(a, items)
a[np.isin(a, items)]

array([70, 10, 70, 90])

np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [20]:
a

array([66, 98, 72, 70, 28, 64, 75, 27, 54, 66,  9, 10, 42, 82, 70, 36, 90,
       75, 22, 32, 32, 12, 74, 14, 26])

In [21]:
np.flip(a)

array([26, 14, 74, 12, 32, 32, 22, 75, 90, 36, 70, 82, 42, 10,  9, 66, 54,
       27, 75, 64, 28, 70, 72, 98, 66])

In [22]:
b

array([[25, 68,  2, 88, 52,  7],
       [22, 94, 75, 34, 15, 47],
       [69, 62, 35, 26, 81, 40],
       [75, 32, 76, 22, 61, 14]])

In [23]:
# 2d array fliping
np.flip(b)

array([[14, 61, 22, 76, 32, 75],
       [40, 81, 26, 35, 62, 69],
       [47, 15, 34, 75, 94, 22],
       [ 7, 52, 88,  2, 68, 25]])

In [24]:
# 2d array fliping -> row wise, axis=1
np.flip(b, axis=1)

array([[ 7, 52, 88,  2, 68, 25],
       [47, 15, 34, 75, 94, 22],
       [40, 81, 26, 35, 62, 69],
       [14, 61, 22, 76, 32, 75]])

In [26]:
# 2d array fliping -> column wise, axis=1
np.flip(b, axis=0)

array([[75, 32, 76, 22, 61, 14],
       [69, 62, 35, 26, 81, 40],
       [22, 94, 75, 34, 15, 47],
       [25, 68,  2, 88, 52,  7]])

# np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [27]:
np.put(a, [0,1], [100,200])  # array, index, change values. put() permanently changes the value


In [28]:
a

array([100, 200,  72,  70,  28,  64,  75,  27,  54,  66,   9,  10,  42,
        82,  70,  36,  90,  75,  22,  32,  32,  12,  74,  14,  26])

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [29]:
np.delete(a,0)   #  array, index

array([200,  72,  70,  28,  64,  75,  27,  54,  66,   9,  10,  42,  82,
        70,  36,  90,  75,  22,  32,  32,  12,  74,  14,  26])

In [31]:
np.delete(a,[1,2,3,4])  # multiple value delete

array([100,  64,  75,  27,  54,  66,   9,  10,  42,  82,  70,  36,  90,
        75,  22,  32,  32,  12,  74,  14,  26])

# Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [34]:
import numpy as np

In [36]:
# union1d
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
# intersect1d
np.intersect1d(m,n)

array([3, 4, 5])

In [43]:
# setdiff1d
print(np.setdiff1d(m,n))
print(np.setdiff1d(n,m))


[1 2]
[6 7]


In [44]:
# setxor1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [46]:
# in1d    -> finding values
np.in1d(m, 1)    # array, value

array([ True, False, False, False, False])

In [48]:
np.in1d(m, [1,2,3]) # multiple values

array([ True,  True,  True, False, False])

# np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [49]:
a

array([100, 200,  72,  70,  28,  64,  75,  27,  54,  66,   9,  10,  42,
        82,  70,  36,  90,  75,  22,  32,  32,  12,  74,  14,  26])

In [50]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 72, 70, 28, 64, 75, 27, 54, 66, 25, 25, 42, 75, 70, 36, 75,
       75, 25, 32, 32, 25, 74, 25, 26])