<a href="https://colab.research.google.com/github/AzadMehedi/Numpy/blob/main/Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([43, 82,  8, 40, 60, 93, 91, 22, 37, 65, 32, 50, 95, 15,  8])

In [2]:
# sort
np.sort(a)

array([ 8,  8, 15, 22, 32, 37, 40, 43, 50, 60, 65, 82, 91, 93, 95])

In [6]:
# decending order sort 
np.sort(a)[::-1]

array([95, 93, 91, 82, 65, 60, 50, 43, 40, 37, 32, 22, 15,  8,  8])

In [7]:
b = np.random.randint(1,100, 24).reshape(6,4)
b

array([[90, 82, 48, 83],
       [49, 38, 51, 88],
       [29, 95, 62, 44],
       [38,  3, 80, 60],
       [88, 31, 20, 70],
       [60,  4, 46, 97]])

In [8]:
# row wise sorting -> (axis=1) . its default
np.sort(b)

array([[48, 82, 83, 90],
       [38, 49, 51, 88],
       [29, 44, 62, 95],
       [ 3, 38, 60, 80],
       [20, 31, 70, 88],
       [ 4, 46, 60, 97]])

In [11]:
# column wise sorting -> (axis=0) . its default
np.sort(b, axis=0)

array([[29,  3, 20, 44],
       [38,  4, 46, 60],
       [49, 31, 48, 70],
       [60, 38, 51, 83],
       [88, 82, 62, 88],
       [90, 95, 80, 97]])

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
a = np.random.randint(1,100,15)
np.append(a, 500)

array([ 53,  73,  13,  97,  68,  22,  62,  76,  46,  27,  23,  65,  70,
        87,  53, 500])

In [16]:
# append a new col
b = np.random.randint(1,100, 24).reshape(6,4)
np.append(b,np.ones((b.shape[0],1)), axis=1)
# np.append(b,np.random.random((b.shape[0],1)), axis=1)


array([[20., 92., 50., 13.,  1.],
       [77., 64., 14., 44.,  1.],
       [60., 63., 62., 22.,  1.],
       [28., 27., 78., 27.,  1.],
       [83., 38., 94., 44.,  1.],
       [93., 42., 89., 69.,  1.]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [19]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
# vertical concatenate -> row wise
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# horizontal concatenate -> column wise
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [25]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [26]:
a

array([53, 73, 13, 97, 68, 22, 62, 76, 46, 27, 23, 65, 70, 87, 53])

In [29]:
np.expand_dims(a, axis=0)
# np.expand_dims(a, axis=0).shape   


(1, 15)


In [30]:
np.expand_dims(a, axis=1)
# np.expand_dims(a, axis=1).shape   



(15, 1)

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html